### ISSUE TITLE
"dont have the proper permission" but i have

### ISSUE THREAD

**Issue by Lesaloon** [ThirtyVirus/UberItems_CustomAddon_Template#2]
i tryed to give my friend an item and disalow it for everyone else so i made the main group have the -uber.item.the item name

and to my friend i gave the tag uber.item.the item name

but its that he dont have proper permission

and me too i cant use this item but i'm an admin and have all the perm

`
UberItems.putItem("raptor_sword",
                new raptor_sword(
                        Material.WOODEN_SWORD,
                        "La lame du raptor",
                        UberRarity.SPECIAL,
                        false,
                        false,
                        true,
                Collections.singletonList(new UberAbility("Poison",
                        AbilityType.NONE,
                        "Donne Poisson et naussée a toutes les entiter qui seront toucher par cette épée")),
                new UberCraftingRecipe(Arrays.asList(
                        new ItemStack(Material.BARRIER),
                        new ItemStack(Material.POISONOUS_POTATO),
                        new ItemStack(Material.BARRIER),
                        new ItemStack(Material.POISONOUS_POTATO),
                        new ItemStack(Material.WOODEN_SWORD),
                        new ItemStack(Material.POISONOUS_POTATO),
                        new ItemStack(Material.BARRIER),
                        new ItemStack(Material.POISONOUS_POTATO),
                        new ItemStack(Material.BARRIER)), false, 1)));
`

and 

`
public boolean hitEntityAction(Player player, EntityDamageByEntityEvent event, Entity target, ItemStack item) {
        LivingEntity victim = (LivingEntity) target;
        victim.addPotionEffect((new PotionEffect(PotionEffectType.CONFUSION, 2, 1)));
        victim.addPotionEffect((new PotionEffect(PotionEffectType.POISON, 10, 1)));
        return false;
    }
`

hoping this code will help figue out my problem

**Comment by sinender** [comment]
Could you send me any logs of you opening the recipe inventory?

**Comment by Lesaloon** [comment]
is that what your asking ? 

`
[22:10:53]: [ERROR] Could not pass event CraftItemEvent to UberItems v2.1
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
at thirtyvirus.uber.events.inventory.RenameItem.playerCraftEvent(RenameItem.java:46) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.16.5.jar:git-Paper-634]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-634]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-634]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2701) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1262) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-634]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-634]
at java.lang.Thread.run(Thread.java:834) [?:?]
`

**Comment by sinender** [comment]
Yes it is and it has to do with the item name

**Comment by Lesaloon** [comment]
the item displayed name is "La lame du raptor" i dont think there is any problem i mean no spetial character or anything wierd

and for the id its  "raptor_sword" i dont think the _sword is problematic 

so do you have any clue 


if not i will just tryal and error the name and id

**Comment by sinender** [comment]
ill try it aswell and see what i can do

**Comment by Lesaloon** [comment]
ok thx

**Comment by Lesaloon** [comment]
i made an other item and the it is not working too


`
UberItems.putItem("lesaloon_mask",
                new lesaloon_mask(
                        Material.LEATHER,
                        "Masque de 2nd personaliter",
                        UberRarity.SPECIAL,
                        false,
                        false,
                        true,
                        Collections.singletonList(new UberAbility("2nd voix",
                                AbilityType.RIGHT_CLICK,
                                "")),
                        new UberCraftingRecipe(Arrays.asList(
                                new ItemStack(Material.LEATHER),
                                new ItemStack(Material.LEATHER),
                                new ItemStack(Material.LEATHER),
                                new ItemStack(Material.LEATHER),
                                new ItemStack(Material.LEATHER_HELMET),
                                new ItemStack(Material.LEATHER),
                                new ItemStack(Material.LEATHER),
                                new ItemStack(Material.LEATHER),
                                new ItemStack(Material.LEATHER)), false, 1)));
`

**Comment by Lesaloon** [comment]
i changed the rarity for the 2nd item and it worked

i go try w/ the first

**Comment by Lesaloon** [comment]
idk why but i cant use special and very special item even if i have the "uber.rarity.*" on true

so wierd but solved 

thx sinender for your help
